"""add password column to user

Revision ID: 8cba74311fa6
Revises: f97f29921d53
Create Date: 2025-10-06 20:37:32.043634

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8cba74311fa6"
down_revision = "f97f29921d53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
