"""add preferred language to user table

Revision ID: af814f7b55d0
Revises: ce8973086d91
Create Date: 2026-03-07 16:39:27.073518

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af814f7b55d0"
down_revision = "ce8973086d91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "preferred_language", sa.String(length=10), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferred_language")

    # ### end Alembic commands ###
