"""add category

Revision ID: f97f29921d53
Revises: dbd5124873bf
Create Date: 2025-09-11 19:59:07.099828

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f97f29921d53"
down_revision = "dbd5124873bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index("idx_name", ["name"], unique=False)

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_notes_category_id", "categories", ["category_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_constraint("fk_notes_category_id", type_="foreignkey")
        batch_op.drop_column("category_id")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index("idx_name")

    op.drop_table("categories")
    # ### end Alembic commands ###
